In [2]:
# Importing the libraries

import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
# Importing the dataset

path = "/content/drive/MyDrive/ARMY/learn-ai/deepLearning/Part 1 - Artificial Neural Networks"
dataset = pd.read_csv(path + "/Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
# Label Encoding the "Gender" column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [5]:
# Label Encoding the "Geography" column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = ct.fit_transform(X)

In [6]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
# Initializing the ANN

ann = tf.keras.models.Sequential()

In [9]:
# Adding the input layer and the first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [10]:
# Adding the second hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [11]:
# Adding the output layer

ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [17]:
# Compiling the ANN

ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [18]:
# Training the ANN on the Training set

ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7960 - loss: 0.5343
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7949 - loss: 0.4700
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7981 - loss: 0.4468
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8069 - loss: 0.4355
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8082 - loss: 0.4374
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8118 - loss: 0.4295
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8122 - loss: 0.4291
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8117 - loss: 0.4327
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8277 - loss: 0.4139
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8219 - loss: 0.4179
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8267 - loss: 0.4107
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [20]:
# Predicting the result of a single observation

ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[0.07436942]], dtype=float32)

In [31]:
# Predicting the Test set results

y_pred = ann.predict(X_test) > 0.5
np.concatenate([y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)], 1)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [32]:
# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred), accuracy_score(y_test, y_pred)

(array([[1543,   52],
        [ 256,  149]]),
 0.846)